[project]
name = "arxiv-explorer"
version = "0.1.0"
description = "An mcp that explore arxiv database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.9",
    "fastapi>=0.116.1",
    "fastmcp>=2.11.3",
    "python-dotenv>=1.1.1",
    "tavily-python>=0.7.10",
]
